first_django_project/urls.py
from tkinter.font import names

from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

# პირველრგიში სანად pathში შევუქმნით ენდფოინთს და გავუწერთ ფუქნციას, ეს ფუქნციები უნდა დავაიმპორტოთ



# urlpatterns = [
#     path('admin/', admin.site.urls),
#     # მას შემდეგ რაც დავაიმპორტებთ, pathში ჯერ უნდა გავუწეროთ ენდფოინთი, ისევე როგორც flaskში ვუწერდით,
#     # რათა ბრაუზერში ამ ენდფოინთის გამოძახბისას მიაკითხოს იმ ფუნქციას რომელსაც pathში გავუწერთ
#     path('index/' , index, name='index'),
#     # ფუნქციასთან ერთად უნდა დავუწეროთ nameიც, რომელიც შემდეგომში ამ ორ გვერდს შორის დასაკავშირებლად უნდა გამოვიყენოთ
#
#     path('about/', about, name='about'),
# ]

# მაგრამ ყველა ენდფოინთი რომ არ ვწეროთ ხელით,
# ამის ნაცვლად უმჯობესია რომ urls.py  ფაილი შევქმნათ აპლიკაციაში, და უშალოდ ამ ფაილში გავწროთ ენდფოინთები,
# ხოლო ამ ენდფოინთების ასამუშავებლად კი includeის გამოყენებით აქ წამოვიღოთ ეს ენდფოინთები და აქედან ავამუშავოთ
# includes გამოსაყენებლად კი ჯერ path თან ერთად უნდა დავაიმპორტოთ

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('user/', include('user.urls', namespace='user')),

# თუკი route ში დავტოვებთ ცარიელს სტრინგს, მაშინ აპლიკაციაში გადასვლა არ მოგვიწევს ენდფოინთების გამოსაძახებლად
# მაგრამ თუკი მეორე აპლიკაციასაც შევქმნით და დავამატებთ, მაშინ ორიცე ცარიელი არ უნდა დავტოვოთ, წინააღმდეგ შემთხვევაში წაიკითხავს იმას რომელიც პირველი წერია
] + debug_toolbar_urls()
# აპლიკაციის ენდფოინთები გავწერეთ უშუალოდ აპლიკაციაშივე შექმნილ urls ფაილში რომელსაც ვიძახებთ includeდან
# ხოლო იმისათვის რომ ამ ენდფოინთებზე შევიდეთ, ჯერ უნდა შევიდეთ უშუალოდ აპლიკაციაში და შემდეგ შევიდეთ აპლიკაციის ენდფოინთებზე

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import (
    HomeView, products_json,
    ProductDetailView, ProductCreateView, ProductUpdateView,
    ProductDeleteView, ProductListView
)
from django.views.generic import TemplateView


app_name = "store"

# ყველა ენდფოინთი urls.py გაწერის ნაცვლად უმჯობესია თითოეულ აპლიკაციას შიგნითვე შევუქმნათ urls ფაილი
# და ამავე ფაილში გავუწეროთ ეს ენდფოინთები,
# ხოლო ამ ენდფოინთების ასამუშავებლად კი includesს გამოყენებით წავიღოთ urls.py ფაილში
# ამ მიდგომით თითოეული ენდფოინთი იქნება აპლიკაციაში და მათ გამოსაძახებლად
#ი pathში ჯერ უნდა შევიდეთ აპლიკაციაში შემდეგ კი შევიდეთ ამ ენდფოინთებზე

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    # თუკი routeს ცარიელს დავტოვებთ, მაშინ ენდფოინთის გამოძახების გარეშე გაეშვება ეს გვერდი
    # მარგამ მხოლოდ ერთხელ შეგვიძლია ენდფოინთის ცარეილი დატოვება
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('products.json/', products_json, name='products_json'),
    path('products/',  ProductListView.as_view(), name='product_list'),
    path('products/<int:product_pk>/', ProductDetailView.as_view(), name='product_details'),
    path('add_product/', ProductCreateView.as_view(), name='add_product'),
    path('update_product/<int:product_pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:product_pk>/', ProductDeleteView.as_view(), name='delete_product'),



# რადგანაც მეორე პარამეტრიც გადავეცით ფუნქციას, routeში ახალი path უნდა შევუქმნათ, აქ შემოდის ის რითიც უნდა დავიჭიროთ id,
# თუკი მონაცემთა ბაზიდან წამოვა id 3, მაშინ აქ უნდა დაიჭიროს 3იანი, რის შემდეგაც გამოიტანს იმ მონაცემს რომლის ID იქნება 3

# ენდფოინთის შემქნის შემდეგ ინდა დავუწვას / დახრილი ხაზი და <> მეტობა ნაკლებობის ნიშანში უნდა გავუწეროთ
# 1: მონაცემი ტიპი, რა მონაცემის ტიპი უნდა შემოვიდეს
# 2: უშუალოდ ჩვენს მიერ ფუქნციაში გადაცემულ პარამეტრი, რათა ეს პარამეტრი დაიჭიროს, როცა ამ პარამეტრს დაიჭერს,
# ფუქნციაში ეს მონაცემი გაუტოლდება ID ის და ამ აიდით წამოიღებს მონაცემს რომელიც დაგვიბრუნდება ვიზუალურად
# მაგრამ იმ შემთხვევაშ თუკი ID არ არსებობს საიტი გავა ერორზე, იმისათვის რომ ერორზე არ გავიდეს, ვიყენებთ get_object_404, თუ პროდუქტი იქნება დააბრუნებს ამ პროდუქტს
# ხოლო თუ არ იქნება მაშინ გამოიტანს რომ პროდუქტი არ არსებობს / ეს get_object_404 უნდა დავაიმპორტოთ და გამოვიყენოთ ფუქნციაშივე >>>
]



# ფუნქციის შემდეგ გაწერილ nameებს ვიყენებთ იმისათვის რომ html დოკუმენტეი დავაკავშიროთ ერთმანეთს, nameში გაწერილ სახელებს კი ამ კავშირისატვის ვიყენებთ
# ეს კავშირი კი უშუალოდ html დოკუმენტში უნდა შევქმნათ, რისთვისაც ვიყენებთ jinja2 ის ენას
# a href თეგით უნდა დავაკავშიროთ, ხოლო jinjas ენით კუ უნდა შევქმნათ დამაკავშირებელი ლინკი
# {% url 'store:about' %}
# ფიგურულ ფრჩხილებში უნდა დავუწეროთ პროცემტის ნიშანი {% %} შიგნით კი უნდა ავაგოთ url,
# ჯერ უნდა დავუწეროთ url და შემდეგ კი აპლიკაციის დასახელება და ის სახელი რომელიც pathში გავუწერეთ nameში

user/urls.py
from django.urls import path
from user.views import (
    UserRegistrationView, UserLoginView, UserLogoutView
)


app_name = 'user'


urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

templates/partials/footer.html
<div class="card">
  <div class="card-header">
    Quote
  </div>
  <div class="card-body">
    <figure>
      <blockquote class="blockquote">
        <p>A well-known quote, contained in a blockquote element.</p>
      </blockquote>
      <figcaption class="blockquote-footer">
        Someone famous in <cite title="Source Title">Source Title</cite>
      </figcaption>
    </figure>
  </div>
</div>

templates/partials/navbar.html
<div class="container">
     <nav class="navbar navbar-expand-lg bg-body-tertiary">
         <div class="container-fluid">
             <a class="navbar-brand" href="#">Navbar</a>
             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
             </button>
             <div class="collapse navbar-collapse" id="navbarSupportedContent">
                 <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'store:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'store:product_list' %}">products</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'store:about' %}">about us</a>
                    </li>
                    {% if user.is_authenticated %}
                    {# user.is_authenticatd ავტომატურად ახორციელებს მომხმარებლის აუთენთიკაციას და თუკი დალოგინებულია მაშინ გამოუტან აამუშავებს if ბლოკს > profile და logout ის გვერდებს #}
                    {# ხოლო თუ არ არის დალოგინებული მეორე > else ბლოკზე გადავა და გამოუტანს login და register გვერდებს#}
                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user }}
                            {#  user ცვლადი არ მოგვაქვს, მაგრამ djangoში > settingsში > contextpreccessorsში არის გაწერილი, ასევე django>admin გვერდზეც ავტომატურად არის ჩაშენებული და აქედან მოაქვს #}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="#">Profile</a>
                            </li>
                            <li>
                                <form action="{% url 'user:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button class="dropdown-item">Log Out</button>
                                </form>
                            </li>
                        </ul>
                        </li>
                    {% else %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:login' %}">Log In</a>
                     </li>
                     <li  class="nav-item">
                        <a class="nav-link" href="{% url 'user:register' %}">Register</a>
                     </li>
                    {% endif %}
                 </ul>
                 <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
         </div>
     </nav>
</div>