first_django_project/urls.py
from tkinter.font import names

from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

# პირველრგიში სანად pathში შევუქმნით ენდფოინთს და გავუწერთ ფუქნციას, ეს ფუქნციები უნდა დავაიმპორტოთ



# urlpatterns = [
#     path('admin/', admin.site.urls),
#     # მას შემდეგ რაც დავაიმპორტებთ, pathში ჯერ უნდა გავუწეროთ ენდფოინთი, ისევე როგორც flaskში ვუწერდით,
#     # რათა ბრაუზერში ამ ენდფოინთის გამოძახბისას მიაკითხოს იმ ფუნქციას რომელსაც pathში გავუწერთ
#     path('index/' , index, name='index'),
#     # ფუნქციასთან ერთად უნდა დავუწეროთ nameიც, რომელიც შემდეგომში ამ ორ გვერდს შორის დასაკავშირებლად უნდა გამოვიყენოთ
#
#     path('about/', about, name='about'),
# ]

# მაგრამ ყველა ენდფოინთი რომ არ ვწეროთ ხელით,
# ამის ნაცვლად უმჯობესია რომ urls.py  ფაილი შევქმნათ აპლიკაციაში, და უშალოდ ამ ფაილში გავწროთ ენდფოინთები,
# ხოლო ამ ენდფოინთების ასამუშავებლად კი includeის გამოყენებით აქ წამოვიღოთ ეს ენდფოინთები და აქედან ავამუშავოთ
# includes გამოსაყენებლად კი ჯერ path თან ერთად უნდა დავაიმპორტოთ

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('user/', include('user.urls', namespace='user')),

# თუკი route ში დავტოვებთ ცარიელს სტრინგს, მაშინ აპლიკაციაში გადასვლა არ მოგვიწევს ენდფოინთების გამოსაძახებლად
# მაგრამ თუკი მეორე აპლიკაციასაც შევქმნით და დავამატებთ, მაშინ ორიცე ცარიელი არ უნდა დავტოვოთ, წინააღმდეგ შემთხვევაში წაიკითხავს იმას რომელიც პირველი წერია
] + debug_toolbar_urls()
# აპლიკაციის ენდფოინთები გავწერეთ უშუალოდ აპლიკაციაშივე შექმნილ urls ფაილში რომელსაც ვიძახებთ includeდან
# ხოლო იმისათვის რომ ამ ენდფოინთებზე შევიდეთ, ჯერ უნდა შევიდეთ უშუალოდ აპლიკაციაში და შემდეგ შევიდეთ აპლიკაციის ენდფოინთებზე

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import (
    HomeView, products_json,
    ProductDetailView, ProductCreateView, ProductUpdateView,
    ProductDeleteView, ProductListView
)
from django.views.generic import TemplateView


app_name = "store"

# ყველა ენდფოინთი urls.py გაწერის ნაცვლად უმჯობესია თითოეულ აპლიკაციას შიგნითვე შევუქმნათ urls ფაილი
# და ამავე ფაილში გავუწეროთ ეს ენდფოინთები,
# ხოლო ამ ენდფოინთების ასამუშავებლად კი includesს გამოყენებით წავიღოთ urls.py ფაილში
# ამ მიდგომით თითოეული ენდფოინთი იქნება აპლიკაციაში და მათ გამოსაძახებლად
#ი pathში ჯერ უნდა შევიდეთ აპლიკაციაში შემდეგ კი შევიდეთ ამ ენდფოინთებზე

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    # თუკი routeს ცარიელს დავტოვებთ, მაშინ ენდფოინთის გამოძახების გარეშე გაეშვება ეს გვერდი
    # მარგამ მხოლოდ ერთხელ შეგვიძლია ენდფოინთის ცარეილი დატოვება
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('products.json/', products_json, name='products_json'),
    path('products/',  ProductListView.as_view(), name='product_list'),
    path('products/<int:product_pk>/', ProductDetailView.as_view(), name='product_details'),
    path('add_product/', ProductCreateView.as_view(), name='add_product'),
    path('update_product/<int:product_pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:product_pk>/', ProductDeleteView.as_view(), name='delete_product'),



# რადგანაც მეორე პარამეტრიც გადავეცით ფუნქციას, routeში ახალი path უნდა შევუქმნათ, აქ შემოდის ის რითიც უნდა დავიჭიროთ id,
# თუკი მონაცემთა ბაზიდან წამოვა id 3, მაშინ აქ უნდა დაიჭიროს 3იანი, რის შემდეგაც გამოიტანს იმ მონაცემს რომლის ID იქნება 3

# ენდფოინთის შემქნის შემდეგ ინდა დავუწვას / დახრილი ხაზი და <> მეტობა ნაკლებობის ნიშანში უნდა გავუწეროთ
# 1: მონაცემი ტიპი, რა მონაცემის ტიპი უნდა შემოვიდეს
# 2: უშუალოდ ჩვენს მიერ ფუქნციაში გადაცემულ პარამეტრი, რათა ეს პარამეტრი დაიჭიროს, როცა ამ პარამეტრს დაიჭერს,
# ფუქნციაში ეს მონაცემი გაუტოლდება ID ის და ამ აიდით წამოიღებს მონაცემს რომელიც დაგვიბრუნდება ვიზუალურად
# მაგრამ იმ შემთხვევაშ თუკი ID არ არსებობს საიტი გავა ერორზე, იმისათვის რომ ერორზე არ გავიდეს, ვიყენებთ get_object_404, თუ პროდუქტი იქნება დააბრუნებს ამ პროდუქტს
# ხოლო თუ არ იქნება მაშინ გამოიტანს რომ პროდუქტი არ არსებობს / ეს get_object_404 უნდა დავაიმპორტოთ და გამოვიყენოთ ფუქნციაშივე >>>
]



# ფუნქციის შემდეგ გაწერილ nameებს ვიყენებთ იმისათვის რომ html დოკუმენტეი დავაკავშიროთ ერთმანეთს, nameში გაწერილ სახელებს კი ამ კავშირისატვის ვიყენებთ
# ეს კავშირი კი უშუალოდ html დოკუმენტში უნდა შევქმნათ, რისთვისაც ვიყენებთ jinja2 ის ენას
# a href თეგით უნდა დავაკავშიროთ, ხოლო jinjas ენით კუ უნდა შევქმნათ დამაკავშირებელი ლინკი
# {% url 'store:about' %}
# ფიგურულ ფრჩხილებში უნდა დავუწეროთ პროცემტის ნიშანი {% %} შიგნით კი უნდა ავაგოთ url,
# ჯერ უნდა დავუწეროთ url და შემდეგ კი აპლიკაციის დასახელება და ის სახელი რომელიც pathში გავუწერეთ nameში

user/urls.py
from django.urls import path
from user.views import (
    UserRegistrationView, UserLoginView, UserLogoutView
)


app_name = 'user'


urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

store/forms.py
from django import forms
from store.models import Product, Category


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('is_active',)

store/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from store.models import Product, Category
from store.forms import ProductForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy

# ListView - გამოიყენება მონაცემების სიის გამოსატანად
# DetailView - გამოიყენება მონაცემების დეტალების გამოსატანად
# CreateView - გამოიყენება მონაცემების დასამატებლად


# views.py ვწერთ ფუნქციების სახით ლოგიკებს რომლებიც მომხმარებლისთვის ვიზუალურად იქნება ხილული.
# მას შემდეგ რაც ამ ფუნქციას შევქმნით, იმისათვის რომ უშუალოდ ვიზულურად გამოვიტანოთ ბრაუზერში,
# ფუნქციის დასახელება უნდა გავწეროთ urls ფაილში urlpatterns ლისტში,
# სადაც უნდა შევუქმნათ ენდფოინთი და ამ ფუნციის დასახელება გავუწეროთ, რათა ენდფოინთის გამოძახებისას უშუალოდ ამ ფუნქციას მიაკითხოს

        # def index(request):
        #     # ფუნქციას აუცილებლად უნდა გადავცეთ request პარამეტრი
        #     return HttpResponse("<h1>Hello, world. You're at the polls index.</h1>")
# ბოლოს კი  httpresponse ში უნდა დავაბრუნებინოთ მონაცემი რასაც ვიზუალურად გამოიტანს, შეგვიძლია html ის კოდიც გავწეროთ შიგნით

        # def about(request):
        #     return HttpResponse("<h2>Hello, world. You're at the polls about.</h2>")
# მაგრამ ის მიგდომა რომ html კოდი httpresponseში დავწეროთ არის არასწორია
# ამიტომ შეგვიძლია ცალკე html კოდი დავწეროთ და უშუალოდ ეს კოდი დავარენდეროთ ფუნქციაში,
# ამისათვის ვიყენებთ დაიმპორტებულ render და არა httpresponse
# def index(request):
#     # მსგავსად httpresponseისა, უნდა გადავცეთ request პარამეტრი,
#     return render(request, "index.html")
# # ხოლო renderს კი უნდა დავაბრუნებინოთ request და html ფაილი,
# # ამისათვის, აუცილებლად უნდა შევქმნათ template საქაღალდე, რომელშიც უნდა შევინახოთ html ფაილები, საქაღალდეს აუცილებლად უნდა დავარქვათ templates

class HomeView(TemplateView):
    template_name = 'index.html'



    # def about(request):
            # return render(request, "about.html")
# ხოლო, შეგვიძლია about გვერდიც ისევე ავაწყოთ როგორც IndexView
    # class AboutView(TemplateView):
    #     template_name = 'about.html'
# მაგრამ, შეგვიძლია კლასი არ შევქმმნათ და უშუალოდ urlsში დავაიმპორტოთ TemplateView, და TemplateView.as_view()ს ფრჩხილებში გადავცეთ
# template_name='about.html', ფრჩხილებში უნდა გადავცეთ ის template რაც უნდა დაამუშავოს
# უშუალოდ pathშივე უნდა გავუწეროთ



# index და aboutის შემთხვევაში, რომელიც მონაცემებს არ ემუშავება და მხოლოდ კონკრეტული ფაილი გამოაქვს
# შეგვიძლია გამოვიყენოთ TemplateView













# #############################################################################################################################
# ბაზიდან მონაცემების წამოღება და ამ მონაცემების გამოსახვა ჩვენს გვერდზე, ამისათვის ჯერ models ფაილიდან უნდა დავაიმპორტოთ მონაცემები
# შემდეგ კი ORM ის საშუალებით უნდა წამოვიღოთ ეს მონაცემები ფუნქციაში
def products_json(request):
    all_products = Product.objects.all()
    # ბოლოს კი JsonResponseთი უნდა დავაბრუნებინოთ, Json ობიექტის სახით გარდაქმნიოს მონაცემებს და ისე გამოიტანს
    return JsonResponse({'products_json' : list(all_products.values())})
    # ლისტად გადავაქციეთ ეს მონაცემები რათა სერიალიზაციის დროს Jsonმა წაიკითხოს და დააბრუნოს
    # რადგანაც all_product ჩვენს მიერ დაწერილი კლასია, ვერ დაასერიალიზებს

# მაგრამ იმისათვის რომ ჩვენვე წამოვიღოთ ეს მონაცემი და ვიზუსლურად გამოვიტანოთ საიტზე, ამისათვის საჭიროა რომ contextით გავატანოთ ეს მონაცემი
# contextში ის ცვლადი უნდა გავატანოთ რომელშიც ORMით წამოღებული მონაცემები გვაქვს შენახული, ხოლო უშუალოდ ამ მონაცემის გამოსახვა კი უნდა მოხდეს html დოკუმენტიდან jinjaს ენის საშუალებით
        # def product_list(request):
        #     all_product = Product.objects.all().select_related('categories').order_by('-created_at')
        #     total_products = all_product.count()
        #     return render(request, "products.html", {'products' : all_product})
# <!--  იმისათვის რომ ბექიდან წამოღებული მონაცემი გამოვსახოთ ვიყენებთ ჯინჯას ენას, context ით გამოტანებული ცვლადის გამოსახვა შეგვიძლია {{ context_name }} ით,
# მაგრამ გამოიტანს query_setს დიქტის სახით, იმისათვის რომ დალაგებული და ვიზუალურად გარჩევადი იყოს შეგვიძლია გადავიაროთ for ციკლით და სათითაოდ გამოვიტანოთ ისინი  -->
# <!-- for ციკლიცთვის ან if ბლოკისათვის ვიყენებთ {% %} ფიგურული ფრჩხილები და პროცენტის ნიშანი შიგნით, ხოლო ცვლადის გამოსატანად კი უშუალოდ {{}} ორი ფიგურული ფრჩხილები  -->
# შეგვიძლია forიდან ამოღებულ მონაცემების ატრიბუტებიც გამოვიტანოთ მხოლოდ




# როგორც ვიცით viewsში ფუნქციებში იწერება ლოგიკები, რომელიც ვიზუალურაად გამოიტანს ფაილებში დაწერილ დოკუმენტაციას
# მაგრამ, გარდა ფუნქციებისა შეგვიძლია კლასებშიც გავწეროთ ეს ლოგიკები, რასაც პროგრამირებაში ვუწოდებთ classed_based_view CBV
# ეს CBV ჩაშენებულია djangoში, რომელის შესაძლებლობები შეგვიძლია გამოვიყენოთ ჩვენს მიერ შექმნილ viewში
# ჯერ უნდა დავაიმპორტოთ viewები from django.views.generic import Views
# productეის გვერდი გადავაკეთოთ CBVად
class ProductListView(ListView):
    # model ში უნდა გადავცეთ იმ მოდელის/ცხრილის დასახელება რომელიც უნდა გამოსახოს, რომელი მოდელიდანაც გვინდა მონაცემის წამოღება
    model = Product

    # template_nameს უნდა გადავცეთ html ის ფაილი, რომელშიც უნდა გამოსახოს ეს მონაცემი
    template_name = "products.html"

    # context_objects_name როგორც ფუნქციაში ვაბრუნებინებდით კონტექსტის სახით მონაცემებს, რომელსაც შემდგომ ვიყენებდით მონაცეების გამოსასახად, მსგავსად
    context_object_name = "products"
    # დეფაულტად context_object_name დააბრუნდეს იმ მოდელის ყველა პროდუქციას, რომლსაც model = ში გადავცემთ
    # ამის ფუნქციონალი გაწერილი აქვს მშობელ კლასში / ან შეგვიძლია context_processorsში გავატანოთ მონაცემი
    # იმ შემთხვევაში თუკი, კლასიდან გადავატნთ მონაცემს და არა context_processorsდან, მაშინ მოთხოვნების შესამცირებლად querysetში უნდა გავიწეროთ select_related()
    queryset = Product.objects.all().select_related('categories')
    # პირდაპირ select_raletedს ვერ მოვდებთ, ჯერ წვდომა უნდა განვახორციელოთ Productზე და მერე მოვდოთ

    # პაგინაცია აკეთებს რომ ერთ გვერდზე მაქსიმუმ რამდენი პროდუქტი უნდა გამოიტანოს, ალაგებს პროდუქციას რაღაც ლოგიკის მიხედვით,
    paginate_by = 6 # ერთ გვერდზე გამოიტანს მხოლოდ 3 პროდუქტს, დანარცენის ნახვა კი სხვა გვერდებზე იქნება შესაძლებელი
    # პაგინაციის ენდფოინთი იწერება ?page=N რომელ გვერდზეც ვართ იმის ნომერი გაეწერება nში

    # პაგინაციების გვერდის შექმნა კი ხდება html დოკუმენტაციაში
    # პაგინაციას გაჩნია რამდენიმე ჩაშენებული ცვლადიც:
    # is_paginated - გვაქვს თუ არა პაგინაცია გაკეთებული
    # num_pages - რამდენი გვერდი გვაქვს
    # page_obj.number - რომელ გვერდზეც ვართ იმას გამოიტანს
    # object_list - არსებულ გვერდზე მონაცემებს გამოიტანს query_setის სახით
    # page_obj -რამდენი გვერდიცაა, ამ გვერდებიდან რომელ გვერდზე ვართ ჩვენ - ანუ მაგ თუა 3 გვერდი და ვართ 2 გვერდზე გამოიტანს რომ ვართ page 2 of 3
    # page_obj.has_previous - რომელ გვერდზეც ვართ, იმ გვერდს აქვს თუ არა წინა გვერდი
    # page_obj.has_next - რომელ გვერდზეც ვართ, იმ გვერდს აქვს თუ არა შემდეგი გვერდი

    # page_obj.previous_page_number - რომელ გვერდზეც ვართ იმ გვერდს თუ აქვს წინა გვერდი ამ გვერდის ნომერს გამოიტანს
    # page_obj.next_page_number - რომელ გვერდზეც ვართ იმ გვერდს თუ აქვს შემდეგი გვერდი ამ გვერდის ნომერს გამოიტანს
    # ზემო ორი ცვლადის შემთხვევაში თუ ვართ პირველ ან ბოლო გვერდზე, რადგანაც მათ არ აქვთ წინა ან შემდეგი გვერდი, გავა ერორზე

    # paginator.page_range - რამდენ გვერდიც გვაქვს იმ გვერდების რეინჯს გამოიტანს, როგორც range ფუნქცია მუშაობდა ისე იმუშავებს




    # იმ შემთხვევაში თუკი კლასსს ერთზე მეტი მოდელი უნდა გავატანოთ,
    # მაგ: კლასს productების გარდა უნდა გავატანოთ ბოლოს დამატებული 5 პროდუქცია, ამისათვის ვიყენებთ არა context_objects_manager არამედ ვიყენებთ მეთოდს def context_data
    def get_context_data(self, **kwargs):
        # მეთოდმა ჯერ მშობლის მონაცემები უნდა წამოიღოს, და შემდეგ გადავუტვირთოთ
        context = super().get_context_data(**kwargs)
        # superით უნდა გამოვიძახოთ მშობლის მეთოდი და გადავტვირტოთ

        # ისევ context უნდა გადავტვირთოთ,1: ჯერ ცვლადს უნდა გავუწეროთ პირდაპირ context სახელი, რომელსაც კონტრქსტით გატანს და უშუალოდ ამას გამოვიყენებთ html კოდში
        # 2: context უნდა გადავტვირთოთ და ახალი მონაცემი გავატანოთ
        context['last_five_product'] = self.queryset.order_by('-created_at')[:5]
        context['count'] = self.queryset.count()
        # ყოველი ახალი მონაცემის გამოსატანად, contextს უნდა გავუწეროთ ['context_name']  = ახალი მონაცემის წამოღება
        # ბოლოს კი context უნდა დავაბრუნოთ
        return context


    # ordering = გადაეცემა მნიშვნელობა, რომლის მიხედვითაც დაალაგებს ჩვენს მონაცემეს, შეგვიძლია გადავცეთ ფასი, სახელი, შექმნის დრო, ხელმისაწვდომობა და ა შ.
    # ordering = ['-created_at']

# მას შემდეგ რაც ავაწყობთ CBVს, urlsშიც უნდა შევუცვალოთ პარამეტრები, კონკრეტულად ფუნქციიდან უნდა გადავაკეთოთ კლასად და pathში კლასი უნდა გავუწეროთ
# მაგრამ pathში პირდაპირ კლასს ვერ გავუწერთ, არამედ კლასი უნდა გამოვიძახოთ, ბოლოში უნდა გავუწეროთ class_name.as_view() - as_view() უნდა გავუწეროთ




# მონაცემის დამატება:
# def add_product(request):
#     if request.method == "POST":
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("store:product_list")
#     else:
#         form = ProductForm()
#     return render(request, "add_product.html", {'form' : form})


# გადავტვირთოთ add_productიც classებად
class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = "add_product.html"
    # განსხვავებით ფუნქციისა არაა საჭირო გავუწეროთ if ბლოკი, requestის ფრომა და ა შ

    # მარტივად უნდა გადავცეთ ფორმის კლასი
    form_class = ProductForm

    # მონაცემის დამატების შემთხვევაში რომელ გვერდზე გადაგვიყვანოს, აწ ვუწერთ ენდფოინთის დასახელებას
    def get_success_url(self, **kwargs):
        return reverse_lazy("store:product_details", kwargs={'product_pk': self.object.pk})

    # თუკი მომხმარებელი არ არის დალოგინებული მაშინ გადაიყვანოს login ფეიჯზე

store/templates/about.html
{% extends 'base.html' %}
{% block title %}About us{% endblock %}


{% block content %}
    <h1>Hello from about page</h1>
    <p>{{ last_five_product }}</p>
    <ul>
    {% for product in all_products %}
        <li>
        {{ product }}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

store/templates/product_details.html
{% extends 'base.html' %} {# extends ბლოკი არ იხურება}
{% block title %}{{ product.title }} Details{%endblock%}

{% block content %}
</head>
<body>
    <h2>Products full information</h2>
    <div class="row container">
        <div class="card col-md-4" style="width: 18rem;">
             {% if product.image %}
                <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ product.title }}</h5>
                <p class="card-text">description: {{ product.description }}</p>
                <p class="card-text">quantity: {{ object.quantity}}</p>
                <p class="card-text">In stock: {{object.is_active}}</p>
                <a href="{% url 'store:product_list' %}">Back to Products</a>
                <p class="card-text">{{ product.price }}$</p>
            </div>
        </div>
    </div>
    <a href="{% url 'store:update_product' object.pk %}" class="btn btn-secondary bg-success mt-4 w-25">Update product</a>
    <form action="{% url 'store:delete_product' object.pk %}" method="post" onsubmit="return confirm('Confirm to Delete product')">
        {% csrf_token %}
        <button class="btn btn-secondary bg-danger mt-4 w-25">Delete product</button>
    </form>
{% endblock %}

store/templates/products.html
{% extends 'base.html' %} {# extends ბლოკი არ იხურება}
{% block title %}Products{%endblock%}

{% block content %}
    <h1 class="mb-4">Hello from products page</h1>
    <div class="row">
        {% for product in products %}
        <div class="card col-md-3 mb-4 ms-5 h-100" style="height:100px">
            {% if product.image %}
            <img src="{{ product.image.url }}" class="card-img-top" alt="..." style="height:150px">
            {% endif %}
            <div class="card-body" style="height:250px">
                <h5 class="card-title fs-6 bg-primary">{{ product.title }}</h5>
                <p class="card-text">{{ product.price }}</p>
                <p class="card-text">{{ product.description }}</p>
                <a href="{% url 'store:product_details' product.id %}" class="btn btn-primary">Click to see details</a>
                <p>Category: {{ product.categories }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <hr>
    <a href="{% url 'store:add_product'  %}" class="btn btn-secondary bg-success mt-4 w-25">Add product</a>
    <h2>total_product: {{ count }}</h2>



<!-- პაგინაციის გვერდი-->
    <hr>
    {{ paginator.page_range }}
<!--პირველ რიგში უნდა შევამოქმოთ რომ თუ პაგინაცია შექმნილია მაშინ გამოიტანოს პაგინაციის გვრდი-->
    {% if is_paginated %}
    <nav aria-label="..." class="d-flex justify-content-center">
      <ul class="pagination">
<!-- პაგინაციის ფუნქციონალური გვერდები რომ ავაწყოთ უნდა გავუწეროთ მათი მისამართების ენდფოინთები -->
<!-- პირველ გვერდს შეგვიძლია მანუალურად გავუწეროთ რომ იყოს პირველი გვერდი განსხვავებით ბოლოსგან -->

<!-- წინა გვერდზე რომ გადავიდეთ, ამის შესაქმნელად შეგვიძლია გავუწეროთ რომ ?page= უდრიდეს, წინა გვერდს,
ამისათვის ვიყენებთ page_obj.previous_page_number, ოღონდ ეს უნდა ჩავსვათ ჯინჯას სინტაქსში, მაგრამ როგორ ვიცით თუკი გვერდს არ ექნება წინა ან შემდეგი გვწერდი,
მაშინ გავაერორზე, ამისათვის უნდა გამოვიყენოთ if ბლოკი და გავაკეთოთ ვალიდაცია, თუ გვერს აქვს წინა გვერდი მაშინ გაუშვას ბლოკში არსებული html დოკუმენტაცია -->
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1" aria-label="Previous">&laquo; First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev...</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">&laquo; First</a></li>
            <li class="page-item disabled"><a class="page-link">Prev...</a></li>
        {% endif %}

        <!-- ხოლო შუაში არსებულ გვერდებზე გადასასვლელად გვჭირდება რომ for ციკლით გადავიაროთ pageებზე -->
        {% for page in paginator.page_range %}
        <!-- ეს გამოგვიტანს ყველა იმ გვერდების რაოდენობას, რამდენი გვერდიც გვაქვს -->
        <!-- აქ კი შეგვიძლია, რომ ის გვერდი რომელზეც ვართ გამოკვეთილად გამოვაჩინოთ, ამისათვის ისევ უნდა გამოვიყენოთ if ბლოკი, რომ num უნ და უდრიდეს  -->
            {% if page == page_obj.number %}
                <li class="page-item active"><a class="page-link" aria-current="page">{{ page }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" aria-current="page" href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}


<!-- რადგანაც არ ვიცით რამდენი გვერდი შეიძლება გვქონდეს, ამიტომ შეგვიძლია გავუწეროთ რომ ბოლო გვერდი იყო რამდენი გვერდიც გვაქვს იმდენი ციფრი, მაგ თუკი გაიზარდა ფეიჯების გვერდი მაშინ ბოლო გვერდის ციფრის შეიცვლება -->
<!-- როგორც previous გვერდს გავუკეთეთ ვალიდაცია ისევე უნდა გავუკეთოთ nextსაც, მაგრამ უნდა გამოვიყენოთ next და არა previous -->
          {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ paginator.num_pages }}" aria-label="Previous">Last &raquo;</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link">Next</a></li>
            <li class="page-item disabled"><a class="page-link">Last &raquo;</a></li>
          {% endif %}
      </ul>
    </nav>
    {% endif %}



{% endblock %}